### PR TITLE
Update the Google Play screenshots and flow.

### PR DESCRIPTION
**Pull request by bbewan**
https://app.asana.com/0/353548986073982/354500184072008

### CODE REVIEW

**Comment by bbdocs** [comment]
See the website here: http://58-bb-docs.surge.sh

**Comment by kevin-bb** [comment]
I don't know if this is for this flow or a different, but if you look at: http://58-bb-docs.surge.sh/deployments/android/google_play/manual.html

`Next, select the variant dropdown and select the variant you want to upload to Google Play.`

The wording should talk about selecting a release variant and that if a release variant is not selected, none will show up... but doesn't really have to do with this change as far as I know.

**Comment by bbewan** [comment]
@kevin-bb I'm not completely clear about the guidance you're suggesting, and there may be multiple points involved. Do users need to know to select "release" variants, as opposed to any other variants that might be listed in the dropdown?

Also, what does "none will show up" mean if the user does not select a release variant... does "show up" refer to Google Play? Or, possibly, do you suppose we need to explain how dropdown menus work here?

**Comment by bbdocs** [comment]
See the website here: http://58-bb-docs.surge.sh

**Comment by kevin-bb** [comment]
I am good with merging this PR, btw. But to answer above.

As far as releasing to the Google Play store, they must select Release variants. However, if it says no variants are available, this is generally the reason because they haven't built a release variant. 

We should explain how the drop downs should work. We should say that if there isn't a variant in the drop-down that it is because a release variant has not been built by buddybuild. Since you can have debug variants built but they won't show up in the list.

**Comment by bbdocs** [comment]
See the website here: http://58-bb-docs.surge.sh

**Pull request merged**
