### PR TITLE
Add a Contact us page

### PR DESCRIPTION
**Pull request by bbewan**
https://app.clubhouse.io/buddybuild/story/7247/create-a-contact-us-page

Includes some capitalization fixes through the table of contents.

### CODE REVIEW

**Comment by bbdocs** [comment]
See the website here: http://121-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://121-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://121-bb-docs.surge.sh

**Comment by richiebres** [comment]
* searching for `support` or `help` should link to this page.
* ensure that google searches for "buddybuild support" or "buddybuild help" hit this page
* we should make it clear that Intercom is our *primary* means or the best way to contact us

**Comment by bbdocs** [comment]
And add that if the widget isn’t visible to email us.

**Comment by bbdocs** [comment]
See the website here: http://121-bb-docs.surge.sh

**Pull request merged**
