### PR TITLE
Add note about iTunes Connect delays.

### PR DESCRIPTION
**Pull request by bbewan**
https://app.asana.com/0/353548986073982/432420222003324

Also includes a couple of other minor tweaks.

### CODE REVIEW

**Comment by matt-adam** [comment]
Looks good -- you could also mention that Apple will send you an email when they're done processing the build?

**Comment by bbdocs** [comment]
See the website here: http://83-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://83-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://83-bb-docs.surge.sh

**Pull request merged**
