### PR TITLE
Add coverage of Danger.

### PR DESCRIPTION
**Pull request by bbewan**
https://app.clubhouse.io/buddybuild/story/6904/add-coverage-for-danger
https://app.clubhouse.io/buddybuild/story/6903/adjust-danger-example-in-custom-build-steps-to-run-in-postbuild-not-finally-since-it-can-t-fail-the-build-from-finally

### CODE REVIEW

**Comment by bbdocs** [comment]
See the website here: http://154-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://154-bb-docs.surge.sh

**Comment by bbewan** [comment]
Links added, but I'm not sure whether they're the official targets. Can you take another look?

**Comment by bbdocs** [comment]
See the website here: http://154-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://154-bb-docs.surge.sh

**Pull request merged**
