### PR TITLE
Rename `INDEX.adoc` to `index.adoc` to avoid case issues. Plus an adjustment to the Travis workflow.

### PR DESCRIPTION
**Pull request by bbewan**

### CODE REVIEW

**Comment by bbdocs** [comment]
See the website here: http://11-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://11-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://11-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://11-bb-docs.surge.sh

**Comment by bbewan** [comment]
Thoughts and question:
- I don't think we need the website URL for each PR update. We can live with it if ensuring only one exists is going to take notable effort.
- I think we do need reviewer approval for PRs.
- I think we need Danger included. Once you have the initial inclusion, I can update the Danger logic.
- Are you okay with the changes I made to `.travis.yml` ?

**Comment by davidascher** [comment]
1) true we don't need the comment on each comment, I don't know how to avoid that trivially.
2) done
3) I'll look into danger, haven't done that before.
4) yes.

**Pull request merged**
