### PR TITLE
Update Ruby versions

### PR DESCRIPTION
**Pull request by bbewan**
https://app.clubhouse.io/buddybuild/story/9251/update-documentation-for-added-deprecated-rubies

### CODE REVIEW

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Comment by nathanshox** [comment]
@bbewan I messed up when I read your comment in Clubhouse.

For a period of time we're going to also have the older versions of ruby on the seed as well. so the full list for iOS is going to be

- 2.2.5 # Deprecated
- 2.2.9
- 2.3.1 # Deprecated
- 2.3.6
- 2.4.1 # Deprecated
- 2.4.3
- 2.5.0

Then later, we'll remove the ones marked deprecated. Basically right now we're just _adding_ new rubies.

**Comment by bbewan** [comment]
Thanks @nathanshox ; I've added the deprecated versions.

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Comment by nathanshox** [comment]
The final list of rubies has changed slightly. Defaults are in bold. I don't know what is on El Capitan or Yosemite, but so few customers are on those VMs I don't think we need to call them out.

| Sierra | High Sierra |
| ------------- | ------------- |
| **ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]** | 2.2.5 |
| 2.2.5 | 2.2.9|
| 2.2.9 | 2.3.1 |
| 2.3.1 | **2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]** |
| 2.3.6 | 2.3.6 |
| 2.4.1 | 2.4.1 |
| 2.4.3 | 2.4.3 |
| 2.5.0 | 2.5.0 |

We're probably not going to go to the effort of removing any rubies so you don't need to mention they're deprecated.

**Comment by bbdocs** [comment]
See the website here: http://159-bb-docs.surge.sh

**Pull request merged**
